# SPDX-License-Identifier: GPL-2.0

# platform driver
snd-soc-mt6789-afe-y := \
	mt6789-afe-pcm.o \
	mt6789-afe-clk.o \
	mt6789-afe-gpio.o \
	mt6789-dai-adda.o \
	mt6789-afe-control.o \
	mt6789-dai-i2s.o \
	mt6789-dai-hw-gain.o \
	mt6789-dai-pcm.o \
	mt6789-dai-src.o \
	mt6789-dai-hostless.o \
	mt6789-misc-control.o

obj-$(CONFIG_SND_SOC_MT6789) += snd-soc-mt6789-afe.o
obj-$(CONFIG_SND_SOC_MT6789_MT6366) += mt6789-mt6366.o
